amp/urls.py
from amp import views
from django.urls import path
from django.shortcuts import redirect
# app_name = 'amp'
# handler500 = views.handler500

urlpatterns = [
    path('', views.PostList, name='amp_home'),
    path('tag/<slug:slug>/amp', views.tagged, name="tagged_amp"),    
    path('kategori/<slug:slug>/amp', views.KategoriShow, name='kategori_show_amp'),
    path('read/<slug:slug>/amp', views.PostDetail, name='amp_post_detail'),
]

# handler404 = views.handler404

blog/urls.py
from . import views
from django.urls import path



urlpatterns = [
    path('', views.PostList, name='home'),
    path('list-user/', views.list_user, name='list_user'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.sitemaps import PostSitemap, Halamansitemap
from blog.models import Kategori, Post
from django.views.static import serve
from blog import views
from django.views.generic.base import TemplateView
from taggit.models import Tag
from django.template.response import TemplateResponse
from django.views import View

admin.site.site_header = "Panel | Admin"
admin.site.site_title = "Admin"
admin.site.index_title = "Welcome"

sitemaps = {
    "page": Halamansitemap,
    "kategori": GenericSitemap(
        {"queryset": Kategori.objects.all(), "changefreq": "daily"},
        priority=0.9,
    ),
    "posts": PostSitemap,
}

class OneSignalSDKView(View):
    def get(self, request, *args, **kwargs):
        return TemplateResponse(
            request=request,
            template="notif/{}".format(kwargs["path"].split("?")[0]),
            content_type="application/javascript",
        )

class PWA(View):
    def get(self, request, *args, **kwargs):
        return TemplateResponse(
            request=request,
            template="pwa/{}".format(kwargs["path"].split("?")[0]),
            content_type="application/javascript",
        )

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("amp/", include("amp.urls")),
    # path('404/', views.handler404, name='404'),
    # path('500/', views.handler500, name='500'),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(
        r"^amp/media/(?P<path>.*)$",
        serve,
        {"document_root": settings.MEDIA_ROOT},
    ),
    re_path(
        r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_DIR}
    ),
    re_path(
        r"^amp/static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_DIR}
    ),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("sitemap.xml/", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="blog/robots.txt", content_type="text/plain"),
    ),
    re_path(r"^(?P<path>OneSignalSDK.*)$", OneSignalSDKView.as_view()),
    re_path(r"^(?P<path>pwabuilder.*)$", PWA.as_view()),
    re_path(r"^amp/(?P<path>OneSignalSDK.*)$", OneSignalSDKView.as_view()),
    re_path(r"^amp/(?P<path>pwabuilder.*)$", PWA.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

handler404 = views.hand404
handler500 = views.hand500

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager
from django.urls import reverse

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Kategori(models.Model):
    kategori = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.kategori

    def get_absolute_url(self):
        return reverse('kategori_show', args=[str(self.kategori)])


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = RichTextUploadingField(blank=True, null=True)
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE, related_name='blog_kategori')
    tags = TaggableManager()
    banner = models.ImageField(upload_to='banner_pics', blank=True)
    meta_deskripsi = models.TextField(null=True, verbose_name='Caption')
    meta_keyword = models.CharField(max_length=200, unique=False, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    is_headline = models.BooleanField(default=False)  # New field to indicate if it's a headline

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("post_detail", kwargs={"slug": str(self.slug)})


class Dokumen(models.Model):
    STATUS_CHOICES = [
        ('belum', 'Belum Terverifikasi'),
        ('terverifikasi', 'Terverifikasi'),
    ]

    PROGRAM_PENDIDIKAN_CHOICES = [
        ('SMP', 'SMP'),
        ('SMA', 'SMA'),
    ]

    nama = models.CharField(max_length=200)
    document = models.FileField(upload_to='user_documents/')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uploaded_documents', null=True, blank=True)
    program_pendidikan = models.CharField(max_length=3, choices=PROGRAM_PENDIDIKAN_CHOICES, default='SMP')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='belum')

    def __str__(self):
        return self.nama

    def status_display(self):
        return dict(self.STATUS_CHOICES)[self.status]

blog/forms.py
# forms.py
from django import forms
from .models import Dokumen

class DokumenForm(forms.ModelForm):
    class Meta:
        model = Dokumen
        fields = ['nama', 'document', 'program_pendidikan']  # Sertakan program_pendidikan di sini

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Kategori, Dokumen
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import random
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse
from taggit.models import Tag
from django.template.context import RequestContext
from django.db.models import Q
from csp.decorators import csp_exempt
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import * 
from rest_framework.views import APIView
from rest_framework import viewsets, status
from .forms import DokumenForm
from django.contrib import messages
import random

class ListViewSet(APIView):
    def get(self, request):
        datanya = Post.objects.filter(status=1).all()
        serializer = ArticleSerializer(datanya, many=True)
        return Response(serializer.data)

def docs(request):
    # response = redirect('/')
    # return response
    return render(request,"blog/lozad.html") 

def pindah(request, id, slug):
    # Gunakan get_object_or_404 untuk mengambil objek Post berdasarkan ID
    post = get_object_or_404(Post, id=id, status=1)

    # Sekarang Anda memiliki objek 'post' yang sesuai dengan ID yang diberikan
    # Anda dapat melakukan apa pun yang Anda inginkan dengan objek ini, misalnya, mengirimkannya ke template
    return render(request, "blog/detailpost.html", {'post': post})

def cari(request):
    q = request.GET.get('q')

    print(q)
    return HttpResponse("asdasd")

# search view
@csp_exempt
def search(request):
    if request.is_ajax():
        q = request.GET.get('q')
        if q is not None:            
            results = Post.objects.filter(  
            	Q( title__contains = q ) |
                Q( slug__contains = q ),status=1  )[:7]          
            # print(results.query)
            return render(request,'blog/hasilcari.html', {'results': results})

@csp_exempt
def PostList(request):
    kategori = Kategori.objects.all()
    queryset = Post.objects.filter(status=1).order_by('-created_on').select_related('kategori')
    randompost = random.sample(list(queryset), min(len(queryset), 3))

    # Menambahkan definisi latest_headline
    headline_list = Post.objects.filter(is_headline=True, status=1)[:4]

    # Menambahkan query untuk mendapatkan data program_pendidikan
    program_pendidikan_data = Dokumen.objects.values('program_pendidikan').distinct()

    if request.method == 'POST':
        dokumen_form = DokumenForm(request.POST, request.FILES)
        if dokumen_form.is_valid():
            dokumen = dokumen_form.save(commit=False)

            # Tambahkan pengecekan apakah pengguna terotentikasi
            if request.user.is_authenticated:
                dokumen.user = request.user
                messages.success(request, 'Dokumen berhasil diunggah oleh pengguna terotentikasi. Terima kasih!')
            else:
                # Pengguna tidak terotentikasi, set user ke None
                dokumen.user = None
                messages.success(request, 'Dokumen berhasil diunggah tanpa login. Terima kasih!')

            dokumen.save()

    else:
        dokumen_form = DokumenForm()

    # Tidak menggunakan Paginator untuk menampilkan semua posting
    post_list = queryset

    data = {
        'data': queryset,
        'post_list': post_list,
        'randompost': randompost,
        'kategori': kategori,
        'headline_list': headline_list,
        'dokumen_form': dokumen_form,
        'program_pendidikan_data': program_pendidikan_data,
    }

    return render(request, "blog/index.html", data)

@csp_exempt
def list_user(request):
    dokumen_list = Dokumen.objects.all()
    return render(request, 'blog/list_user.html', {'dokumen_list': dokumen_list})

@csp_exempt
def PostDetail(request, slug):
    dt = Post.objects.filter(status=1).select_related('kategori').get(slug=slug)
    # print(dt.slug)
    kategori = Kategori.objects.all()
    queryset = Post.objects.all().filter(status=1)
    randompost = random.sample(list(queryset), min(len(queryset),6))
    data = {
        'post':dt,
        'randompost':randompost,
        'kategori':kategori
    }
    return render(request,"blog/detailpost.html",data)

@csp_exempt
def tagged(request, slug):
    kategori = Kategori.objects.all()
    tag = get_object_or_404(Tag, slug=slug)
    # Filter posts by tag name  
    posts = Post.objects.filter(tags=tag,status=1)
    queryset = Post.objects.all().filter(status=1)
    randompost = random.sample(list(queryset), min(len(queryset),4))
    
    paginator = Paginator(posts, 5)  # 3 posts in each page
    page = request.GET.get('page')
    # q = request.GET.get('q')

    # print(ht)
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
            # If page is not an integer deliver the first page
        post_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        post_list = paginator.page(paginator.num_pages)
    
    context = {
        'slug':slug,
        'hitung':posts.count(),
        'tag':tag,
        'post_list':post_list,
        'randompost':randompost,
        'kategori':kategori,
        'page':page,
    }
    # for x in posts:
        # print(x.created_on)
    return render(request, 'blog/tag.html', context)

@csp_exempt
def KategoriShow(request, slug):
    dt = Post.objects.all().select_related('kategori').filter(status=1,kategori__kategori__contains=slug)
    # for x in dt:
        # print(x)
    # dt = Kategori.objects.all().filter(kategori__contains=slug)
    kategori = Kategori.objects.all()
    namakategori = Kategori.objects.all().filter(kategori__contains=slug).first()
    queryset = Post.objects.all().filter(status=1)
    randompost = random.sample(list(queryset), min(len(queryset),3))
    
    paginator = Paginator(dt, 5)  # 3 posts in each page
    page = request.GET.get('page')
    # q = request.GET.get('q')

    # print(ht)
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
            # If page is not an integer deliver the first page
        post_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        post_list = paginator.page(paginator.num_pages)
    
    data = {
        'namakategori':namakategori,
        'hitung':dt.count(),
        'slug':slug,
        'post':dt,
        'randompost':randompost,
        'kategori':kategori,
        'page':page,
        'post_list': post_list,
    }
    return render(request,"blog/kategori.html",data)

@csp_exempt
def hand404(request,exception):
    queryset = Post.objects.all().filter(status=1)
    kategori = Kategori.objects.all()
    randompost = random.sample(list(queryset), min(len(queryset),4))
    data = {
        'randompost':randompost,
        'kategori':kategori,
    }
    return render(request,"blog/404.html",data)
    
@csp_exempt    
def hand500(request):
    return render(request, 'blog/500.html', status=500)
#     # return HttpResponse(dt)
    
# API
@api_view(['GET', ])
def APIPostList(request):
    kategori = Kategori.objects.all()
    queryset = Post.objects.filter(status=1).all()
    randompost = random.sample(list(queryset), min(len(queryset),4))
    data = []
    nextPage = 1
    previousPage = 1
    paginator = Paginator(queryset, 5)  # 3 posts in each page
    page = request.GET.get('page', 1)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    
    serializer = ArticleSerializer(data,context={'request': request},many=True)
    kat = KategoriSerializer(kategori ,many=True)    
    randompostt = ArticleSerializer(randompost,many=True)
    
    if data.has_next():
        nextPage = data.next_page_number()
    if data.has_previous():
        previousPage = data.previous_page_number()
    
    data = {
        'data':serializer.data,
        'kategori': kat.data,
        'randompost': randompostt.data,
        'halaman': "cobaa",
        'count': paginator.count, 
        'numpages' : paginator.num_pages, 
        'nextlink': '/api/?page=' + str(nextPage), 
        'prevlink': '/api/?page=' + str(previousPage)

    }

    return Response(data)
    # return render(request,"blog/index.html",data) 

def APIPostDetail(request, slug):
    dt = Post.objects.filter(status=1).select_related('kategori').get(slug=slug)
    # print(dt.slug)
    kategori = Kategori.objects.all()
    queryset = Post.objects.all().filter(status=1)
    randompost = random.sample(list(queryset), min(len(queryset),4))
    data = {
        'post':dt,
        'randompost':randompost,
        'kategori':kategori
    }
    return render(request,"blog/detailpost.html",data)

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unggah Dokumen</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-success">
    <div class="container">
        <a class="navbar-brand text-white" href="#">Unggah Bukti Pembayaran</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" href="#">Beranda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="/list-user/">Order File</a>
                </li>
             
            </ul>
        </div>
    </div>
</nav>

<!-- Main Content -->
<div class="container mt-5">
    <h2>Formulir Unggah Dokumen</h2>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nama" class="form-label">Nama Lengkap</label>
            <input type="text" class="form-control" id="nama" name="nama" required>
        </div>
        <div class="mb-3">
            <label for="id_program_pendidikan" class="form-label">Tingkat Pendidikan</label>
            {{ dokumen_form.program_pendidikan }}
        </div>
        <div class="mb-3">
            <label for="dokumen" class="form-label">Pilih Dokumen (.Png, .pdf)</label>
            <input class="form-control" type="file" id="dokumen" name="document" accept=".png, .pdf, .doc, .docx" required>
        </div>
        <button type="submit" class="btn btn-primary">Kirim Bukti Pembayaran</button>
    </form>
</div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/blog/list_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unggah Dokumen</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-success">
    <div class="container">
        <a class="navbar-brand text-white" href="/">Unggah Bukti Pembayaran</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" href="/">Beranda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#">Order File</a>
                </li>
             
            </ul>
        </div>
    </div>
</nav>


<!-- Main Content -->
<div class="container mt-5">
    <h2>Cek Verifikasi Data</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Nama</th>
                <th scope="col">Tingkat Pendidikan</th>
                <th scope="col">Status Verifikasi</th>  <!-- Tambahkan kolom status verifikasi -->
            </tr>
        </thead>
        <tbody>
            {% for dokumen in dokumen_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ dokumen.nama }}</td>
                    <td>{{ dokumen.program_pendidikan }}</td>
                    <td>
                        {% if dokumen.status == 'terverifikasi' %}
                        <span class="badge text-bg-success">Terverifikasi</span> 
                        {% elif dokumen.status == 'belum_terverifikasi' %}
                        <span class="badge text-bg-danger">Belum Terverifikasi</span>
                        {% else %}
                        <span class="badge text-bg-danger">Belum Terverifikasi</span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>